CREATE TABLE "Member" (
  "user_id" INT PRIMARY KEY,
  "username" VARCHAR UNIQUE  ,
  "name" VARCHAR,
  "email" VARCHAR UNIQUE  ,
  "avatar_url" VARCHAR,
  "DOB" DATE,
  "bio" TEXT,
  "gender" VARCHAR,
  "country" VARCHAR,
  "state" VARCHAR,
  "joined_date" DATE  ,
  "isSubscribed" BOOL  
);

CREATE TABLE "watched" (
  "wactched_id" INT PRIMARY KEY  ,
  "film_id" INT  ,
  "user_id" INT  ,
  "date" DATE  
);

CREATE TABLE "Film" (
  "film_id" INT PRIMARY KEY,
  "name" VARCHAR  ,
  "poster" VARCHAR,
  "overview" VARCHAR,
  "original_language" VARCHAR  ,
  "director" VARCHAR  ,
  "runtime" INT  ,
  "studio_id" INT  ,
  "release_date" DATE,
  "rating" DECIMAL  ,
  "top250pos" INT,
  "popularity" DECIMAL
);

CREATE TABLE "Studio" (
  "studio_id" INT PRIMARY KEY,
  "name" VARCHAR  ,
  "location" VARCHAR,
  "founded_year" INT,
  "website_url" VARCHAR
);

CREATE TABLE "Genre" (
  "genre_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "genre_name" VARCHAR UNIQUE  
);

CREATE TABLE "Review" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "review" TEXT  ,
  "spoiler" BOOL DEFAULT false,
  "like_count" INT
);

CREATE TABLE "Watchlist" (
  "user_id" INT  ,
  "film_id" INT  ,
  "watchlist_date" DATE  ,
  PRIMARY KEY ("user_id", "film_id")
);

CREATE TABLE "List" (
  "list_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT  ,
  "name" VARCHAR  ,
  "description" TEXT,
  "film_count" INT  ,
  "created" DATE  ,
  "published" DATE  ,
  "ranked" BOOL  
);

CREATE TABLE "ListFilm" (
  "list_id" INT  ,
  "film_id" INT  ,
  "position" INT  ,
  "description" VARCHAR,
  PRIMARY KEY ("list_id", "film_id")
);

CREATE TABLE "Follow" (
  "follower_id" INT  ,
  "following_id" INT  ,
  PRIMARY KEY ("follower_id", "following_id")
);

CREATE TABLE "LogEntry" (
  "diary_entry_id" INT PRIMARY KEY,
  "user_id" INT  ,
  "film_id" INT  ,
  "review_id" INT  ,
  "date" DATE  ,
  "watched_date" DATE  ,
  "rating" DECIMAL,
  "rewatch" BOOL DEFAULT false,
  "liked" BOOL DEFAULT false
);

CREATE TABLE "FilmGenre" (
  "film_id" INT  ,
  "genre_id" INT  ,
  PRIMARY KEY ("film_id", "genre_id")
);

CREATE TABLE "SubscriptionPlan" (
  "plan_id" INT PRIMARY KEY,
  "plan_name" VARCHAR  ,
  "description" TEXT  ,
  "price" DECIMAL(10,2)  
);

CREATE TABLE "Subscription" (
  "subscription_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT  ,
  "plan_id" INT  ,
  "start_date" DATE  ,
  "end_date" DATE DEFAULT null
);

CREATE TABLE "Person" (
  "person_id" INT PRIMARY KEY,
  "name" VARCHAR UNIQUE  ,
  "bio" VARCHAR,
  "image_url" VARCHAR,
  "gender" VARCHAR
);

CREATE TABLE "CastCrew" (
  "film_id" INT  ,
  "person_id" INT  ,
  "role" VARCHAR,
  "character_name" VARCHAR,
  PRIMARY KEY ("film_id", "person_id", "role")
);

ALTER TABLE "Film" ADD FOREIGN KEY ("studio_id") REFERENCES "Studio" ("studio_id");

ALTER TABLE "LogEntry" ADD FOREIGN KEY ("review_id") REFERENCES "Review" ("review_id");

ALTER TABLE "watched" ADD FOREIGN KEY ("user_id") REFERENCES "Member" ("user_id");

ALTER TABLE "watched" ADD FOREIGN KEY ("film_id") REFERENCES "Film" ("film_id");

ALTER TABLE "Watchlist" ADD FOREIGN KEY ("user_id") REFERENCES "Member" ("user_id");

ALTER TABLE "Watchlist" ADD FOREIGN KEY ("film_id") REFERENCES "Film" ("film_id");

ALTER TABLE "List" ADD FOREIGN KEY ("user_id") REFERENCES "Member" ("user_id");

ALTER TABLE "ListFilm" ADD FOREIGN KEY ("list_id") REFERENCES "List" ("list_id");

ALTER TABLE "ListFilm" ADD FOREIGN KEY ("film_id") REFERENCES "Film" ("film_id");

ALTER TABLE "Follow" ADD FOREIGN KEY ("follower_id") REFERENCES "Member" ("user_id");

ALTER TABLE "Follow" ADD FOREIGN KEY ("following_id") REFERENCES "Member" ("user_id");

ALTER TABLE "LogEntry" ADD FOREIGN KEY ("user_id") REFERENCES "Member" ("user_id");

ALTER TABLE "LogEntry" ADD FOREIGN KEY ("film_id") REFERENCES "Film" ("film_id");

ALTER TABLE "FilmGenre" ADD FOREIGN KEY ("film_id") REFERENCES "Film" ("film_id");

ALTER TABLE "FilmGenre" ADD FOREIGN KEY ("genre_id") REFERENCES "Genre" ("genre_id");

ALTER TABLE "Subscription" ADD FOREIGN KEY ("user_id") REFERENCES "Member" ("user_id");

ALTER TABLE "Subscription" ADD FOREIGN KEY ("plan_id") REFERENCES "SubscriptionPlan" ("plan_id");

ALTER TABLE "CastCrew" ADD FOREIGN KEY ("film_id") REFERENCES "Film" ("film_id");

ALTER TABLE "CastCrew" ADD FOREIGN KEY ("person_id") REFERENCES "Person" ("person_id");